
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: my_portfolio-app
    ports:
      - "9001:80"
    volumes:
      - app_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: my_portfolio-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_portfolio
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  app_data:   # kod aplikacji
  db_data:    # dane bazy
